from .userCreateView import  UserCreateView
from .userDetailView import UserDetailView
from .gestionCitasView import GestionCitasDetailView
from .gestionCitasView import GestionCitasListView
from .gestionCitasView import GestionCitasCreateView
from .gestionCitasView import GestionCitasUpdateView
from .gestionCitasView import GestionCitasDestroyView